name: Build H3

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:  
    - '*'
  pull_request:
    branches:  
    - '*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install arm-none-eabi
      run: sudo apt install gcc-arm-none-eabi
    - name: version
      run: arm-none-eabi-g++ --version
    - name: Install U-Boot tools
      run: sudo apt install u-boot-tools
    - name: make
      run: |
        cd scripts
        ./build_h3-firmware.sh

    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./release/*
        tag: ${{env.strDate}}
        file_glob: true
        overwrite: true
        release_name: ${{env.strDate}} 自动发布
