name: Build H3

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:  
    - '*'
  pull_request:
    branches:  
    - '*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install arm-none-eabi
      run: sudo apt install gcc-arm-none-eabi
    - name: version
      run: arm-none-eabi-g++ --version
    - name: Install U-Boot tools
      run: sudo apt install u-boot-tools
    - name: make
      run: |
        cd scripts
        ./build_h3-firmware.sh
